# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

global islem
islem = ""
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(434, 376)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(434, 376))
        MainWindow.setMaximumSize(QtCore.QSize(434, 376))
        MainWindow.setProperty("denm", "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 130, 281, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn1.setObjectName("btn1")

        self.horizontalLayout.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn2.setObjectName("btn2")

        self.horizontalLayout.addWidget(self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn3.setObjectName("btn3")

        self.horizontalLayout.addWidget(self.btn3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 180, 281, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn4.setObjectName("btn4")
        self.horizontalLayout_2.addWidget(self.btn4)
        self.btn5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn5.setObjectName("btn5")
        self.horizontalLayout_2.addWidget(self.btn5)
        self.btn6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn6.setObjectName("btn6")
        self.horizontalLayout_2.addWidget(self.btn6)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 230, 281, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn7.setObjectName("btn7")
        self.horizontalLayout_3.addWidget(self.btn7)
        self.btn8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn8.setObjectName("btn8")
        self.horizontalLayout_3.addWidget(self.btn8)
        self.btn9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn9.setObjectName("btn9")
        self.horizontalLayout_3.addWidget(self.btn9)
        self.btn_eksi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eksi.setGeometry(QtCore.QRect(330, 130, 88, 34))
        self.btn_eksi.setObjectName("btn_eksi")
        self.btn_arti = QtWidgets.QPushButton(self.centralwidget)
        self.btn_arti.setGeometry(QtCore.QRect(330, 170, 88, 34))
        self.btn_arti.setObjectName("btn_arti")
        self.btn_esittir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_esittir.setGeometry(QtCore.QRect(330, 290, 88, 34))
        self.btn_esittir.setObjectName("btn_esittir")
        self.btn_temizle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_temizle.setGeometry(QtCore.QRect(330, 90, 88, 34))
        self.btn_temizle.setObjectName("btn_temizle")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 280, 281, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn0.setObjectName("btn0")
        self.gridLayout_2.addWidget(self.btn0, 0, 0, 1, 1)
        self.btn_carpma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_carpma.setGeometry(QtCore.QRect(330, 250, 88, 34))
        self.btn_carpma.setObjectName("btn_carpma")
        self.btn_bolme = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bolme.setGeometry(QtCore.QRect(330, 210, 88, 34))
        self.btn_bolme.setObjectName("btn_bolme")
        self.pycalc = QtWidgets.QLabel(self.centralwidget)
        self.pycalc.setGeometry(QtCore.QRect(0, 10, 270, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(12)
        font.setItalic(False)
        self.pycalc.setFont(font)
        self.pycalc.setObjectName("pycalc")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(12, 40, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(32767)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 434, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



        self.btn1.clicked.connect(self.bir_ekle)
        self.btn2.clicked.connect(self.iki_ekle)
        self.btn3.clicked.connect(self.uc_ekle)
        self.btn4.clicked.connect(self.dort_ekle)
        self.btn5.clicked.connect(self.bes_ekle)
        self.btn6.clicked.connect(self.alti_ekle)
        self.btn7.clicked.connect(self.yedi_ekle)
        self.btn8.clicked.connect(self.sekiz_ekle)
        self.btn9.clicked.connect(self.dokuz_ekle)
        self.btn0.clicked.connect(self.sifir_ekle)

        self.btn_eksi.clicked.connect(self.eksi_ekle)
        self.btn_arti.clicked.connect(self.arti_ekle)
        self.btn_bolme.clicked.connect(self.bolme_ekle)
        self.btn_carpma.clicked.connect(self.carpma_ekle)
        self.btn_esittir.clicked.connect(self.islemi_yap)

        self.btn_temizle.clicked.connect(self.hepsini_sil)




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyCalculator"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn_eksi.setText(_translate("MainWindow", "-"))
        self.btn_arti.setText(_translate("MainWindow", "+"))
        self.btn_esittir.setText(_translate("MainWindow", "="))
        self.btn_temizle.setText(_translate("MainWindow", "AC"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btn_carpma.setText(_translate("MainWindow", "x"))
        self.btn_bolme.setText(_translate("MainWindow", "÷"))
        self.pycalc.setText(_translate("MainWindow", "PyCalc by beetlejuicetr(MID)"))


    def bir_ekle(self):
          global islem
          islem = islem + "1"
          self.lineEdit.setText(islem)
    def iki_ekle(self):
         global islem
         islem = islem + "2"
         self.lineEdit.setText(islem)
    def uc_ekle(self):
         global islem
         islem = islem + "3"
         self.lineEdit.setText(islem)
    def dort_ekle(self):
         global islem
         islem = islem + "4"
         self.lineEdit.setText(islem)
    def bes_ekle(self):
         global islem
         islem = islem + "5"
         self.lineEdit.setText(islem)
    def alti_ekle(self):
         global islem
         islem = islem + "6"
         self.lineEdit.setText(islem)
    def yedi_ekle(self):
         global islem
         islem = islem + "7"
         self.lineEdit.setText(islem)
    def sekiz_ekle(self):
         global islem
         islem = islem + "8"
         self.lineEdit.setText(islem)
    def dokuz_ekle(self):
         global islem
         islem = islem + "9"
         self.lineEdit.setText(islem)
    def sifir_ekle(self):
         global islem
         islem = islem + "0"
         self.lineEdit.setText(islem)


    def eksi_ekle(self):
         global islem
         islem = islem + "-"
         self.lineEdit.setText(islem)
    def arti_ekle(self):
         global islem
         islem = islem + "+"
         self.lineEdit.setText(islem)
    def bolme_ekle(self):
         global islem
         islem = islem + "/"
         self.lineEdit.setText(islem)
    def carpma_ekle(self):
         global islem
         islem = islem + "*"
         self.lineEdit.setText(islem)


    def islemi_yap(self):
         global islem
         try:
             islem = eval(islem)
             islem = str(islem)
             self.lineEdit.setText(islem)
         except:
            self.lineEdit.setText("only natural numbers")
            islem = ""
    def hepsini_sil(self):
         global islem
         islem = ""
         self.lineEdit.setText(islem)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
